image: docker:20

variables:
  IMAGE_TAG: chainfusion/dapp:$CI_COMMIT_REF_NAME
  IMAGE_TAG_LATEST: chainfusion/dapp:latest

stages:
  - build

.docker_build_template:
  services:
    - docker:20-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

build-main:
  stage: build
  only:
    - main
  extends: .docker_build_template
  script:
    - docker build -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG_LATEST

build-tags:
  stage: build
  only:
    - tags
  extends: .docker_build_template
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
